spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/crm_users
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: docker
